/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AppRouteImport } from './routes/app'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HandoffsRouteImport } from './routes/handoffs'
import { Route as NeedsInputRouteImport } from './routes/needs-input'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as WebmcpRouteImport } from './routes/webmcp'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as HandoffsIndexRouteImport } from './routes/handoffs.index'
import { Route as HandoffsIdRouteImport } from './routes/handoffs.$id'
import { Route as HelpPublicTokenRouteImport } from './routes/help.$publicToken'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as RecordingsIdRouteImport } from './routes/recordings.$id'
import { Route as SPublicTokenRouteImport } from './routes/s.$publicToken'
import { Route as DemoBenefitsSectionRouteImport } from './routes/demo.benefits.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsRoute = HandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsInputRoute = NeedsInputRouteImport.update({
  id: '/needs-input',
  path: '/needs-input',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const WebmcpRoute = WebmcpRouteImport.update({
  id: '/webmcp',
  path: '/webmcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsIndexRoute = HandoffsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandoffsRoute,
} as any)
const HandoffsIdRoute = HandoffsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HandoffsRoute,
} as any)
const HelpPublicTokenRoute = HelpPublicTokenRouteImport.update({
  id: '/help/$publicToken',
  path: '/help/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const SPublicTokenRoute = SPublicTokenRouteImport.update({
  id: '/s/$publicToken',
  path: '/s/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBenefitsSectionRoute = DemoBenefitsSectionRouteImport.update({
  id: '/demo/benefits/$section',
  path: '/demo/benefits/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/handoffs': typeof HandoffsRouteWithChildren
  '/needs-input': typeof NeedsInputRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/webmcp': typeof WebmcpRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/help/$publicToken': typeof HelpPublicTokenRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/s/$publicToken': typeof SPublicTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/handoffs/': typeof HandoffsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/demo/benefits/$section': typeof DemoBenefitsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/needs-input': typeof NeedsInputRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/webmcp': typeof WebmcpRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/help/$publicToken': typeof HelpPublicTokenRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/s/$publicToken': typeof SPublicTokenRoute
  '/demo': typeof DemoIndexRoute
  '/handoffs': typeof HandoffsIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/demo/benefits/$section': typeof DemoBenefitsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/handoffs': typeof HandoffsRouteWithChildren
  '/needs-input': typeof NeedsInputRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/webmcp': typeof WebmcpRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/help/$publicToken': typeof HelpPublicTokenRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/s/$publicToken': typeof SPublicTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/handoffs/': typeof HandoffsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/demo/benefits/$section': typeof DemoBenefitsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/app'
    | '/dashboard'
    | '/handoffs'
    | '/needs-input'
    | '/recordings'
    | '/settings'
    | '/shared'
    | '/webmcp'
    | '/handoffs/$id'
    | '/help/$publicToken'
    | '/recordings/$id'
    | '/s/$publicToken'
    | '/demo/'
    | '/handoffs/'
    | '/recordings/'
    | '/demo/benefits/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/app'
    | '/dashboard'
    | '/needs-input'
    | '/settings'
    | '/shared'
    | '/webmcp'
    | '/handoffs/$id'
    | '/help/$publicToken'
    | '/recordings/$id'
    | '/s/$publicToken'
    | '/demo'
    | '/handoffs'
    | '/recordings'
    | '/demo/benefits/$section'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/app'
    | '/dashboard'
    | '/handoffs'
    | '/needs-input'
    | '/recordings'
    | '/settings'
    | '/shared'
    | '/webmcp'
    | '/handoffs/$id'
    | '/help/$publicToken'
    | '/recordings/$id'
    | '/s/$publicToken'
    | '/demo/'
    | '/handoffs/'
    | '/recordings/'
    | '/demo/benefits/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  HandoffsRoute: typeof HandoffsRouteWithChildren
  NeedsInputRoute: typeof NeedsInputRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  WebmcpRoute: typeof WebmcpRoute
  HelpPublicTokenRoute: typeof HelpPublicTokenRoute
  SPublicTokenRoute: typeof SPublicTokenRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoBenefitsSectionRoute: typeof DemoBenefitsSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs': {
      id: '/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof HandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-input': {
      id: '/needs-input'
      path: '/needs-input'
      fullPath: '/needs-input'
      preLoaderRoute: typeof NeedsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webmcp': {
      id: '/webmcp'
      path: '/webmcp'
      fullPath: '/webmcp'
      preLoaderRoute: typeof WebmcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs/': {
      id: '/handoffs/'
      path: '/'
      fullPath: '/handoffs/'
      preLoaderRoute: typeof HandoffsIndexRouteImport
      parentRoute: typeof HandoffsRoute
    }
    '/handoffs/$id': {
      id: '/handoffs/$id'
      path: '/$id'
      fullPath: '/handoffs/$id'
      preLoaderRoute: typeof HandoffsIdRouteImport
      parentRoute: typeof HandoffsRoute
    }
    '/help/$publicToken': {
      id: '/help/$publicToken'
      path: '/help/$publicToken'
      fullPath: '/help/$publicToken'
      preLoaderRoute: typeof HelpPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/s/$publicToken': {
      id: '/s/$publicToken'
      path: '/s/$publicToken'
      fullPath: '/s/$publicToken'
      preLoaderRoute: typeof SPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/benefits/$section': {
      id: '/demo/benefits/$section'
      path: '/demo/benefits/$section'
      fullPath: '/demo/benefits/$section'
      preLoaderRoute: typeof DemoBenefitsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HandoffsRouteChildren {
  HandoffsIdRoute: typeof HandoffsIdRoute
  HandoffsIndexRoute: typeof HandoffsIndexRoute
}

const HandoffsRouteChildren: HandoffsRouteChildren = {
  HandoffsIdRoute: HandoffsIdRoute,
  HandoffsIndexRoute: HandoffsIndexRoute,
}

const HandoffsRouteWithChildren = HandoffsRoute._addFileChildren(
  HandoffsRouteChildren,
)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  HandoffsRoute: HandoffsRouteWithChildren,
  NeedsInputRoute: NeedsInputRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  WebmcpRoute: WebmcpRoute,
  HelpPublicTokenRoute: HelpPublicTokenRoute,
  SPublicTokenRoute: SPublicTokenRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoBenefitsSectionRoute: DemoBenefitsSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
